channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - numpy==2.0.2
  - tensorflow-intel==2.18.0
  - tensorflow==2.18.0
name: mlflow-env
