{
 "title": "teste monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Health Check ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLO - 300 ms",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(predict_response_time_seconds_bucket{le=\"0.3\"}[5m])) by (job)\r\n/\r\n  sum(rate(predict_response_time_seconds_count[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job) (rate(predict_response_time_seconds_bucket{job=\"ml_monitoring\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift modelo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "concept_drift", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(job) (changes(predict_queries_total{job=\"ml_monitoring\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift dados",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "data_drift", "legendFormat": "__auto" }
   ]
  }
 ]
}