services:
  application:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    container_name: application
    volumes:
      - ./src/:/app
    ports:
      - 8080:8080 # fast api
      - 8000:8000 # Prometheus metrics
    depends_on:
     - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
