services:
  application:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    container_name: application
    volumes:
      - ./src/:/app
    ports:
      - 5000:5000  
      - 8000:8000
    depends_on:
     - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  jupyter:
    build: 
      context: ./
      dockerfile: ./training_model/Dockerfile
    volumes:
      - ./training_model:/home/jovyan/training_model
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
