channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - ipython==8.29.0
  - jaraco-collections==5.1.0
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - tensorflow-intel==2.18.0
name: mlflow-env
